### ISSUE TITLE
项目是放弃了吗？

### ISSUE THREAD

**Issue by matocool** [Cruii/bilibili-helper-hub#15]
![image](https://user-images.githubusercontent.com/83129369/194464719-01fc9f32-f0b8-4e87-b69c-d5b13c75be3b.png)

**Comment by Cruii** [comment]
设计存在缺陷，准备重新改下，后续会重新部署

**Comment by matocool** [comment]
> 设计存在缺陷，准备重新改下，后续会重新部署

感谢付出
